name: lint

on:
  push:
    branches:
      - master
    paths:
      - '**.sh'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1
        env:
          shellcheck_flags: --exclude=SC1090